# SwiftLint configuration file for Randomusers iOS project

# Paths to include during linting. `--path` is ignored if present.
included:
  - Randomusers

# Paths to ignore during linting. Takes precedence over `included`.
excluded:
  - DerivedData
  - .build
  - fastlane
  - Randomusers/Generated
  - Randomusers/Resources/R.generated.swift

# Rules that will be disabled
disabled_rules:
  - trailing_whitespace
  - todo
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces

# Rules that will be opted in
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - yoda_condition

# Customized rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 3
    error: 5

identifier_name:
  min_length: 2
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - URL
    - x
    - y
    - to
    - at
    - in
    - of
    - up
    - ui
    - vm
    - vc
    - i
    - j
    - k

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - UI
    - ID

# Reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, markdown)
reporter: "xcode"

# Custom rules
custom_rules:
  no_print:
    name: "Print Detection"
    regex: '(?<!\\bfatalError\\()\\bprint\\('
    message: "Prefer using a logger instead of print statements."
    severity: warning

  no_uikit_import_in_domain:
    name: "UIKit Import in Domain Layer"
    regex: 'import\\s+UIKit'
    match_kinds:
      - import
    message: "Domain layer should not import UIKit."
    severity: error
    included: "Randomusers/Domain/"
